// ========================================
// Поймай Жука — Equations Database
// ========================================
// Equations with numeric difficulty levels 1, 2, 3

import type { Equation } from '@/types';

export const equations: Equation[] = [
  // ── Difficulty 1: simple +/- up to 20 ──
  { equation: '5 + 3 =', answer: 8, difficulty: 1 },
  { equation: '6 + 7 =', answer: 13, difficulty: 1 },
  { equation: '7 + 9 =', answer: 16, difficulty: 1 },
  { equation: '5 + 8 =', answer: 13, difficulty: 1 },
  { equation: '8 + 6 =', answer: 14, difficulty: 1 },
  { equation: '9 + 7 =', answer: 16, difficulty: 1 },
  { equation: '9 + 5 =', answer: 14, difficulty: 1 },
  { equation: '3 + 8 =', answer: 11, difficulty: 1 },
  { equation: '4 + 7 =', answer: 11, difficulty: 1 },
  { equation: '2 + 9 =', answer: 11, difficulty: 1 },
  { equation: '1 + 10 =', answer: 11, difficulty: 1 },
  { equation: '5 + 9 =', answer: 14, difficulty: 1 },
  { equation: '7 + 8 =', answer: 15, difficulty: 1 },
  { equation: '6 + 9 =', answer: 15, difficulty: 1 },
  { equation: '2 + 3 =', answer: 5, difficulty: 1 },
  { equation: '4 + 3 =', answer: 7, difficulty: 1 },
  { equation: '6 + 4 =', answer: 10, difficulty: 1 },
  { equation: '3 + 5 =', answer: 8, difficulty: 1 },
  { equation: '4 + 6 =', answer: 10, difficulty: 1 },
  { equation: '7 + 3 =', answer: 10, difficulty: 1 },
  { equation: '8 + 5 =', answer: 13, difficulty: 1 },
  { equation: '2 + 8 =', answer: 10, difficulty: 1 },
  { equation: '8 - 5 =', answer: 3, difficulty: 1 },
  { equation: '10 - 3 =', answer: 7, difficulty: 1 },
  { equation: '10 - 7 =', answer: 3, difficulty: 1 },
  { equation: '11 - 9 =', answer: 2, difficulty: 1 },
  { equation: '9 - 2 =', answer: 7, difficulty: 1 },
  { equation: '7 - 1 =', answer: 6, difficulty: 1 },
  { equation: '6 - 2 =', answer: 4, difficulty: 1 },
  { equation: '8 - 2 =', answer: 6, difficulty: 1 },
  { equation: '14 - 6 =', answer: 8, difficulty: 1 },
  { equation: '13 - 5 =', answer: 8, difficulty: 1 },
  { equation: '15 - 8 =', answer: 7, difficulty: 1 },
  { equation: '13 - 6 =', answer: 7, difficulty: 1 },
  { equation: '14 - 7 =', answer: 7, difficulty: 1 },
  { equation: '13 - 8 =', answer: 5, difficulty: 1 },
  { equation: '12 - 3 =', answer: 9, difficulty: 1 },
  { equation: '14 - 8 =', answer: 6, difficulty: 1 },
  { equation: '13 - 9 =', answer: 4, difficulty: 1 },
  { equation: '15 - 5 =', answer: 10, difficulty: 1 },
  { equation: '11 - 4 =', answer: 7, difficulty: 1 },
  { equation: '10 - 4 =', answer: 6, difficulty: 1 },
  { equation: '9 - 4 =', answer: 5, difficulty: 1 },
  { equation: '8 - 3 =', answer: 5, difficulty: 1 },
  { equation: '7 - 4 =', answer: 3, difficulty: 1 },

  // ── Difficulty 2: +/- up to 40, simple × ÷ ──
  { equation: '12 + 7 =', answer: 19, difficulty: 2 },
  { equation: '14 + 9 =', answer: 23, difficulty: 2 },
  { equation: '18 + 5 =', answer: 23, difficulty: 2 },
  { equation: '15 + 6 =', answer: 21, difficulty: 2 },
  { equation: '21 + 10 =', answer: 31, difficulty: 2 },
  { equation: '16 + 12 =', answer: 28, difficulty: 2 },
  { equation: '19 + 4 =', answer: 23, difficulty: 2 },
  { equation: '13 + 8 =', answer: 21, difficulty: 2 },
  { equation: '13 + 9 =', answer: 22, difficulty: 2 },
  { equation: '11 + 6 =', answer: 17, difficulty: 2 },
  { equation: '6 + 12 =', answer: 18, difficulty: 2 },
  { equation: '4 + 11 =', answer: 15, difficulty: 2 },
  { equation: '4 + 12 =', answer: 16, difficulty: 2 },
  { equation: '1 + 15 =', answer: 16, difficulty: 2 },
  { equation: '3 + 11 =', answer: 14, difficulty: 2 },
  { equation: '4 + 14 =', answer: 18, difficulty: 2 },
  { equation: '2 + 16 =', answer: 18, difficulty: 2 },
  { equation: '3 + 12 =', answer: 15, difficulty: 2 },
  { equation: '5 + 13 =', answer: 18, difficulty: 2 },
  { equation: '2 + 13 =', answer: 15, difficulty: 2 },
  { equation: '2 + 15 =', answer: 17, difficulty: 2 },
  { equation: '10 + 5 =', answer: 15, difficulty: 2 },
  { equation: '8 + 10 =', answer: 18, difficulty: 2 },
  { equation: '6 + 11 =', answer: 17, difficulty: 2 },
  { equation: '6 + 10 =', answer: 16, difficulty: 2 },
  { equation: '25 - 8 =', answer: 17, difficulty: 2 },
  { equation: '30 - 11 =', answer: 19, difficulty: 2 },
  { equation: '22 - 13 =', answer: 9, difficulty: 2 },
  { equation: '28 - 9 =', answer: 19, difficulty: 2 },
  { equation: '27 - 14 =', answer: 13, difficulty: 2 },
  { equation: '35 - 19 =', answer: 16, difficulty: 2 },
  { equation: '29 - 15 =', answer: 14, difficulty: 2 },
  { equation: '26 - 7 =', answer: 19, difficulty: 2 },
  { equation: '20 - 7 =', answer: 13, difficulty: 2 },
  { equation: '22 - 5 =', answer: 17, difficulty: 2 },
  { equation: '25 - 10 =', answer: 15, difficulty: 2 },
  { equation: '19 - 8 =', answer: 11, difficulty: 2 },
  { equation: '17 - 4 =', answer: 13, difficulty: 2 },
  { equation: '30 - 12 =', answer: 18, difficulty: 2 },
  { equation: '15 - 4 =', answer: 11, difficulty: 2 },
  { equation: '18 - 9 =', answer: 9, difficulty: 2 },
  { equation: '16 - 8 =', answer: 8, difficulty: 2 },
  { equation: '18 - 8 =', answer: 10, difficulty: 2 },
  { equation: '20 - 10 =', answer: 10, difficulty: 2 },
  { equation: '19 - 5 =', answer: 14, difficulty: 2 },
  { equation: '22 - 11 =', answer: 11, difficulty: 2 },
  { equation: '18 - 3 =', answer: 15, difficulty: 2 },
  { equation: '21 - 7 =', answer: 14, difficulty: 2 },
  { equation: '24 - 12 =', answer: 12, difficulty: 2 },
  { equation: '12 ÷ 4 =', answer: 3, difficulty: 2 },
  { equation: '14 ÷ 2 =', answer: 7, difficulty: 2 },
  { equation: '16 ÷ 2 =', answer: 8, difficulty: 2 },
  { equation: '16 ÷ 4 =', answer: 4, difficulty: 2 },
  { equation: '15 ÷ 3 =', answer: 5, difficulty: 2 },
  { equation: '18 ÷ 3 =', answer: 6, difficulty: 2 },
  { equation: '18 ÷ 6 =', answer: 3, difficulty: 2 },
  { equation: '18 ÷ 2 =', answer: 9, difficulty: 2 },
  { equation: '20 ÷ 4 =', answer: 5, difficulty: 2 },
  { equation: '20 ÷ 5 =', answer: 4, difficulty: 2 },
  { equation: '21 ÷ 7 =', answer: 3, difficulty: 2 },
  { equation: '7 × 2 =', answer: 14, difficulty: 2 },
  { equation: '9 × 2 =', answer: 18, difficulty: 2 },
  { equation: '5 × 3 =', answer: 15, difficulty: 2 },
  { equation: '3 × 6 =', answer: 18, difficulty: 2 },
  { equation: '4 × 5 =', answer: 20, difficulty: 2 },
  { equation: '5 × 4 =', answer: 20, difficulty: 2 },
  { equation: '3 × 7 =', answer: 21, difficulty: 2 },
  { equation: '4 × 6 =', answer: 24, difficulty: 2 },
  { equation: '6 × 4 =', answer: 24, difficulty: 2 },
  { equation: '8 × 3 =', answer: 24, difficulty: 2 },
  { equation: '9 × 3 =', answer: 27, difficulty: 2 },
  { equation: '3 × 8 =', answer: 24, difficulty: 2 },
  { equation: '7 × 5 =', answer: 35, difficulty: 2 },
  { equation: '5 × 6 =', answer: 30, difficulty: 2 },
  { equation: '3 × 10 =', answer: 30, difficulty: 2 },
  { equation: '22 + 7 =', answer: 29, difficulty: 2 },
  { equation: '40 - 15 =', answer: 25, difficulty: 2 },
  { equation: '19 + 11 =', answer: 30, difficulty: 2 },
  { equation: '14 + 16 =', answer: 30, difficulty: 2 },
  { equation: '18 + 12 =', answer: 30, difficulty: 2 },

  // ── Difficulty 3: larger numbers, complex × ÷ ──
  { equation: '45 - 18 =', answer: 27, difficulty: 3 },
  { equation: '50 - 23 =', answer: 27, difficulty: 3 },
  { equation: '21 + 19 =', answer: 40, difficulty: 3 },
  { equation: '60 - 25 =', answer: 35, difficulty: 3 },
  { equation: '70 - 33 =', answer: 37, difficulty: 3 },
  { equation: '27 + 14 =', answer: 41, difficulty: 3 },
  { equation: '55 - 19 =', answer: 36, difficulty: 3 },
  { equation: '33 + 9 =', answer: 42, difficulty: 3 },
  { equation: '60 - 28 =', answer: 32, difficulty: 3 },
  { equation: '36 ÷ 6 =', answer: 6, difficulty: 3 },
  { equation: '24 ÷ 4 =', answer: 6, difficulty: 3 },
  { equation: '40 ÷ 8 =', answer: 5, difficulty: 3 },
  { equation: '32 ÷ 4 =', answer: 8, difficulty: 3 },
  { equation: '24 ÷ 6 =', answer: 4, difficulty: 3 },
  { equation: '28 ÷ 4 =', answer: 7, difficulty: 3 },
  { equation: '24 ÷ 8 =', answer: 3, difficulty: 3 },
  { equation: '27 ÷ 9 =', answer: 3, difficulty: 3 },
  { equation: '30 ÷ 5 =', answer: 6, difficulty: 3 },
  { equation: '32 ÷ 8 =', answer: 4, difficulty: 3 },
  { equation: '40 ÷ 5 =', answer: 8, difficulty: 3 },
  { equation: '45 ÷ 9 =', answer: 5, difficulty: 3 },
  { equation: '45 ÷ 5 =', answer: 9, difficulty: 3 },
  { equation: '48 ÷ 6 =', answer: 8, difficulty: 3 },
  { equation: '49 ÷ 7 =', answer: 7, difficulty: 3 },
  { equation: '54 ÷ 9 =', answer: 6, difficulty: 3 },
  { equation: '56 ÷ 8 =', answer: 7, difficulty: 3 },
  { equation: '63 ÷ 7 =', answer: 9, difficulty: 3 },
  { equation: '63 ÷ 9 =', answer: 7, difficulty: 3 },
  { equation: '64 ÷ 8 =', answer: 8, difficulty: 3 },
  { equation: '72 ÷ 9 =', answer: 8, difficulty: 3 },
  { equation: '4 × 9 =', answer: 36, difficulty: 3 },
  { equation: '8 × 4 =', answer: 32, difficulty: 3 },
  { equation: '9 × 5 =', answer: 45, difficulty: 3 },
  { equation: '7 × 7 =', answer: 49, difficulty: 3 },
  { equation: '6 × 6 =', answer: 36, difficulty: 3 },
  { equation: '5 × 9 =', answer: 45, difficulty: 3 },
  { equation: '10 × 4 =', answer: 40, difficulty: 3 },
  { equation: '6 × 8 =', answer: 48, difficulty: 3 },
  { equation: '8 × 5 =', answer: 40, difficulty: 3 },
  { equation: '7 × 6 =', answer: 42, difficulty: 3 },
  { equation: '6 × 7 =', answer: 42, difficulty: 3 },
  { equation: '10 × 3 =', answer: 30, difficulty: 3 },
  { equation: '5 × 8 =', answer: 40, difficulty: 3 },
  { equation: '6 × 9 =', answer: 54, difficulty: 3 },
  { equation: '4 × 10 =', answer: 40, difficulty: 3 },
  { equation: '9 × 4 =', answer: 36, difficulty: 3 },
  { equation: '8 × 6 =', answer: 48, difficulty: 3 },
  { equation: '7 × 9 =', answer: 63, difficulty: 3 },
  { equation: '9 × 7 =', answer: 63, difficulty: 3 },
  { equation: '8 × 7 =', answer: 56, difficulty: 3 },
  { equation: '7 × 8 =', answer: 56, difficulty: 3 },
  { equation: '9 × 8 =', answer: 72, difficulty: 3 },
  { equation: '8 × 9 =', answer: 72, difficulty: 3 },
  { equation: '3 × 11 =', answer: 33, difficulty: 3 },
  { equation: '4 × 12 =', answer: 48, difficulty: 3 },
  { equation: '9 × 10 =', answer: 90, difficulty: 3 },
  { equation: '5 × 15 =', answer: 75, difficulty: 3 },
  { equation: '7 × 10 =', answer: 70, difficulty: 3 },
  { equation: '5 × 12 =', answer: 60, difficulty: 3 },
  { equation: '5 × 13 =', answer: 65, difficulty: 3 },
  { equation: '7 × 11 =', answer: 77, difficulty: 3 },
  { equation: '7 × 12 =', answer: 84, difficulty: 3 },
  { equation: '12 × 2 =', answer: 24, difficulty: 3 },
  { equation: '77 ÷ 7 =', answer: 11, difficulty: 3 },
  { equation: '84 ÷ 7 =', answer: 12, difficulty: 3 },
  { equation: '88 ÷ 8 =', answer: 11, difficulty: 3 },
  { equation: '99 ÷ 9 =', answer: 11, difficulty: 3 },
  { equation: '66 ÷ 11 =', answer: 6, difficulty: 3 },
  { equation: '60 ÷ 12 =', answer: 5, difficulty: 3 },
  { equation: '70 ÷ 7 =', answer: 10, difficulty: 3 },
  { equation: '80 ÷ 8 =', answer: 10, difficulty: 3 },
  { equation: '81 ÷ 9 =', answer: 9, difficulty: 3 },
  { equation: '90 ÷ 10 =', answer: 9, difficulty: 3 },
  { equation: '100 ÷ 10 =', answer: 10, difficulty: 3 },
];

/** Get equations appropriate for a given level (progressive difficulty) */
export function getEquationsForLevel(level: number): Equation[] {
  const maxDiff = Math.min(3, Math.floor(level / 3) + 1) as 1 | 2 | 3;
  return equations.filter((eq) => eq.difficulty <= maxDiff);
}

/** Get equations appropriate for a given score (legacy, uses level mapping) */
export function getEquationsForScore(score: number): Equation[] {
  const level = Math.floor(score / 50) + 1;
  return getEquationsForLevel(level);
}

/** Pick a random equation from an array */
export function pickRandomEquation(pool: Equation[]): Equation {
  return pool[Math.floor(Math.random() * pool.length)];
}
