ALTER TABLE public.game_sessions
  ADD COLUMN IF NOT EXISTS level INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS max_combo INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_correct INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_wrong INTEGER NOT NULL DEFAULT 0;
